# Jekyll Specific Stuff
markdown: redcarpet
pygments: true
permalink: /posts/:title
paginate: 10 # the number of post per page
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

# User Options
name: This is my blog
baseurl:   # Leave this blank unless you are using a directory other than the root directory (Do not use a trailing slash '/')
description:
email: aheuermann@gmail.com
twitter:
icon_url: https://en.gravatar.com/userimage/2518790/7fc13aa24eda12ec6f15e4d059b8e032.png?size=200
disqus_shortname: heuio

# Color Options
text_color: '#444444'
accent_color: '#d95e3f'
hover_color: '#a7543f'
subtle_color: '#999999'
subtle_border: '#e9e9e9'
title_color: '#222222'
text_on_accent_color: '#ffffff'
header_background: '#385975'
header_text_color: '#dfe6ec'
header_accent_color: '#ffffff'
header_title_color: '#ffffff'
header_subtle_color: '#597790'
header_subtle_border: '#597790'
background: '#fcfcfc'
post_background:

# Footer
footer_title:
footer_description:
social_links: false
social_links_title: Me on the Web
twitter_url: https://twitter.com/aheuermann
github_url: https://github.com/aheuermann
flickr_url:
instagram_url:
vimeo_url:
facebook_url:
google_plus_url:
pinterest_url:
tumblr_url:
linkedin_url: https://www.linkedin.com/in/andrewheuermann
dribbble_url:
lastfm_url:
rdio_url:
spotify_url:
skype_url:
soundcloud_url:
behance_url:
youtube_url: https://www.youtube.com/user/aheuermann/videos
